name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, backend]  # Ensures this job runs only on your specific self-hosted runner
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Verify working directory
        run: pwd

      - name: List files in root
        run: ls -la

      - name: List files in backend directory
        working-directory: backend
        run: ls -la

      - name: Install dependencies
        working-directory: backend
        run: |
          pip3 install pipenv
          pipenv install

      - name: Create env file
        working-directory: backend
        run: |
          touch .env.production
          echo VITE_API_URL=${{ secrets.DATABASE_URL }} >> .env.production
          cat .env.production

      - name: Deploy to Server
        working-directory: backend
        run: |
          export ENVIRONMENT=production
          pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000
