name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, backend]  # Ensures this job runs only on your specific self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Install dependencies
        run: |
          pip3 install pipenv
          pipenv run

      - name: Create env file
        working-directory: frontend
        run: |
          touch .env.production
          echo VITE_API_URL=${{ secrets.DATABASE_URL }} >> .env.production
          cat .env.production

      - name: Deploy to Server
        run: |
          # Your deployment commands here, e.g., starting uvicorn
          export ENVIRONMENT=production
          pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000
