name: Deploy to S3

on:
  push:
    branches:
      - main # Trigger the workflow on push to the 'main' branch
    paths:
      - frontend/**
      - .github/workflows/deploy_frontend.yml

jobs:
  build:
    runs-on: [self-hosted, frontend]  # Ensures this job runs only on your specific self-hosted runner
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Create env file
        working-directory: frontend
        run: |
          touch .env.production
          echo VITE_API_URL=${{ secrets.VITE_API_URL }} >> .env.production
          cat .env.production

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Build
        working-directory: frontend
        run: pnpm run build

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist s3://allobrain-frontend --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
