name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/deploy_backend.yml

jobs:
  deploy:
    runs-on: [self-hosted, backend]
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'


      - name: Generate requirements.txt
        working-directory: backend
        run: |
          pip3 install pipenv
          pipenv lock
          pipenv requirements > requirements.txt
          cat requirements.txt

      - name: Install dependencies
        working-directory: backend
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install psycopg2-binary

      - name: Create env file
        working-directory: backend
        run: |
          touch .env.production
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env.production
          cat .env.production

      - name: Deploy to Server
        working-directory: backend
        run: |
          sudo apt install screen
          export ENVIRONMENT=production
          nohup python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 & 2>&1 > backend.log &
          echo this should be displayed